=== jorgemachado23/proyectosucab/trunk/sistemas/Reserva Salones UCAB/src/Servidor/reservacionSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/reservacionlSchema"
    xmlns:tns="http://xml.netbeans.org/schema/reservacionlSchema"
    elementFormDefault="qualified" xmlns:ns1="http://xml.netbeans.org/schema/horarioSchema" xmlns:ns0="http://xml.netbeans.org/schema/SalonSchema">
    <xsd:import schemaLocation="../Servidor/horarioSchema.xsd" namespace="http://xml.netbeans.org/schema/horarioSchema"/>
    <xsd:import schemaLocation="../Servidor/SalonSchema.xsd" namespace="http://xml.netbeans.org/schema/SalonSchema"/>
    <xsd:complexType name="datosReservacion">
        <xsd:sequence>
            <xsd:element name="usuario" type="xsd:string" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="fecha" maxOccurs="unbounded" type="xsd:dateTime"></xsd:element>
            <xsd:element name="fechaReservacion" type="xsd:dateTime" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="horaInicial" type="xsd:time" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="horaFinal" type="xsd:time" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="salon" type="xsd:string" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="estado" type="xsd:string" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="tipoUsuario" type="xsd:string" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="reservacion" type="tns:datosReservacion"></xsd:element>
</xsd:schema>

=== jorgemachado23/proyectosucab/sistemas/Web Service/WebService2/WebService2/App_Data/reservacion.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : reservacionSchema.xml
    Created on : June 5, 2009, 2:52 PM
    Author     : Alejandro
    Description:
        Purpose of the document follows.
-->

<ns0:reservacion  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/reservacionlSchema'
   xsi:schemaLocation='http://xml.netbeans.org/schema/reservacionlSchema reservacionSchema.xsd'>
    <ns0:usuario>jorgem</ns0:usuario>
    <ns0:fecha>05-06-2009 15:00</ns0:fecha>
    <ns0:fechaReservacion>Mon, 06/15/2009</ns0:fechaReservacion>
    <ns0:horaInicial>20:00:00</ns0:horaInicial>
    <ns0:horaFinal>22:00:00</ns0:horaFinal>
    <ns0:salon>EC-14</ns0:salon>
    <ns0:estado>Solicitado</ns0:estado>
    <ns0:tipoUsuario>Alumno</ns0:tipoUsuario>

</ns0:reservacion>
