=== jorgemachado23/proyectosucab/trunk/sistemas/Reserva Salones UCAB/src/Servidor/usuarioSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/alumnoSchema"
    xmlns:tns="http://xml.netbeans.org/schema/alumnoSchema"
    elementFormDefault="qualified">
    <xsd:complexType name="datosUsuario">
        <xsd:sequence>
                <xsd:element name="nombre" type="xsd:string"></xsd:element>
                <xsd:element name="apellido" type="xsd:string"></xsd:element>
                <xsd:element name="ci" type="xsd:string"></xsd:element>
                <xsd:element name="escDepFac" type="xsd:string"></xsd:element>
                <xsd:element name="usuario" type="xsd:string"></xsd:element>
                <xsd:element name="password" type="xsd:string"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="usuario">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="alumno" type="tns:datosUsuario"></xsd:element>
                <xsd:element name="profesor" type="tns:datosUsuario"></xsd:element>
                <xsd:element name="encargado" type="tns:datosUsuario"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== jorgemachado23/proyectosucab/trunk/sistemas/Reserva Salones UCAB/src/Servidor/usuarioSchema.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : usuarioSchema.xml
    Created on : June 2, 2009, 5:20 PM
    Author     : Alejandro
    Description:
        Purpose of the document follows.
-->

<ns0:usuario  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/alumnoSchema'
   xsi:schemaLocation='http://xml.netbeans.org/schema/alumnoSchema usuarioSchema.xsd'>
    <ns0:alumno>
        <ns0:nombre></ns0:nombre>
        <ns0:apellido></ns0:apellido>
        <ns0:ci></ns0:ci>
        <ns0:escDepFac></ns0:escDepFac>
        <ns0:usuario></ns0:usuario>
        <ns0:password></ns0:password>
    </ns0:alumno>
    <ns0:alumno>
        <ns0:nombre></ns0:nombre>
        <ns0:apellido></ns0:apellido>
        <ns0:ci></ns0:ci>
        <ns0:escDepFac></ns0:escDepFac>
        <ns0:usuario></ns0:usuario>
        <ns0:password></ns0:password>
    </ns0:alumno>
    <ns0:alumno>
        <ns0:nombre></ns0:nombre>
        <ns0:apellido></ns0:apellido>
        <ns0:ci></ns0:ci>
        <ns0:escDepFac></ns0:escDepFac>
        <ns0:usuario></ns0:usuario>
        <ns0:password></ns0:password>
    </ns0:alumno>
    <ns0:profesor>
        <ns0:nombre></ns0:nombre>
        <ns0:apellido></ns0:apellido>
        <ns0:ci></ns0:ci>
        <ns0:escDepFac></ns0:escDepFac>
        <ns0:usuario></ns0:usuario>
        <ns0:password></ns0:password>
    </ns0:profesor>
    <ns0:profesor>
        <ns0:nombre></ns0:nombre>
        <ns0:apellido></ns0:apellido>
        <ns0:ci></ns0:ci>
        <ns0:escDepFac></ns0:escDepFac>
        <ns0:usuario></ns0:usuario>
        <ns0:password></ns0:password>
    </ns0:profesor>
    <ns0:profesor>
        <ns0:nombre></ns0:nombre>
        <ns0:apellido></ns0:apellido>
        <ns0:ci></ns0:ci>
        <ns0:escDepFac></ns0:escDepFac>
        <ns0:usuario></ns0:usuario>
        <ns0:password></ns0:password>
    </ns0:profesor>
    <ns0:encargado>
        <ns0:nombre></ns0:nombre>
        <ns0:apellido></ns0:apellido>
        <ns0:ci></ns0:ci>
        <ns0:escDepFac></ns0:escDepFac>
        <ns0:usuario></ns0:usuario>
        <ns0:password></ns0:password>
    </ns0:encargado>
    <ns0:encargado>
        <ns0:nombre></ns0:nombre>
        <ns0:apellido></ns0:apellido>
        <ns0:ci></ns0:ci>
        <ns0:escDepFac></ns0:escDepFac>
        <ns0:usuario></ns0:usuario>
        <ns0:password></ns0:password>
    </ns0:encargado>
    <ns0:encargado>
        <ns0:nombre></ns0:nombre>
        <ns0:apellido></ns0:apellido>
        <ns0:ci></ns0:ci>
        <ns0:escDepFac></ns0:escDepFac>
        <ns0:usuario></ns0:usuario>
        <ns0:password></ns0:password>
    </ns0:encargado>

</ns0:usuario>

=== jorgemachado23/proyectosucab/trunk/sistemas/Web Service/WebService2/WebService2/App_Data/usuario.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : usuarioSchema.xml
    Created on : June 2, 2009, 5:20 PM
    Author     : Alejandro
    Description:
        Purpose of the document follows.
-->

<ns0:usuario  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/alumnoSchema'
   xsi:schemaLocation='http://xml.netbeans.org/schema/alumnoSchema usuarioSchema.xsd'>
    <ns0:alumno>
        <ns0:nombre>Jorge</ns0:nombre>
        <ns0:apellido>Machado</ns0:apellido>
        <ns0:ci>12345332</ns0:ci>
        <ns0:escDepFac>informatica</ns0:escDepFac>
        <ns0:usuario>jorgem</ns0:usuario>
        <ns0:password>1234</ns0:password>
    </ns0:alumno>
    <ns0:alumno>
        <ns0:nombre>Alejandro</ns0:nombre>
        <ns0:apellido>Blanco-Uribe</ns0:apellido>
        <ns0:ci>17752613</ns0:ci>
        <ns0:escDepFac>informatica</ns0:escDepFac>
        <ns0:usuario>alejandrob</ns0:usuario>
        <ns0:password>12345</ns0:password>
    </ns0:alumno>
    <ns0:alumno>
        <ns0:nombre>Eduardo</ns0:nombre>
        <ns0:apellido>Makverga</ns0:apellido>
        <ns0:ci>38837483</ns0:ci>
        <ns0:escDepFac>informatica</ns0:escDepFac>
        <ns0:usuario>eduardom</ns0:usuario>
        <ns0:password>2345</ns0:password>
    </ns0:alumno>
    <ns0:profesor>
        <ns0:nombre>Wilmer</ns0:nombre>
        <ns0:apellido>Pereira</ns0:apellido>
        <ns0:ci>9838834</ns0:ci>
        <ns0:escDepFac>informatica</ns0:escDepFac>
        <ns0:usuario>wilmerp</ns0:usuario>
        <ns0:password>7364</ns0:password>
    </ns0:profesor>
    <ns0:profesor>
        <ns0:nombre>Lucia</ns0:nombre>
        <ns0:apellido>Cardoso</ns0:apellido>
        <ns0:ci>1223323</ns0:ci>
        <ns0:escDepFac>informatica</ns0:escDepFac>
        <ns0:usuario>luciac</ns0:usuario>
        <ns0:password>2341</ns0:password>
    </ns0:profesor>
    <ns0:profesor>
        <ns0:nombre>Guillermo</ns0:nombre>
        <ns0:apellido>Garcia</ns0:apellido>
        <ns0:ci>8848594</ns0:ci>
        <ns0:escDepFac>informatica</ns0:escDepFac>
        <ns0:usuario>guillermog</ns0:usuario>
        <ns0:password>23132</ns0:password>
    </ns0:profesor>
    <ns0:encargado>
        <ns0:nombre>leonardo</ns0:nombre>
        <ns0:apellido>puga</ns0:apellido>
        <ns0:ci>2323</ns0:ci>
        <ns0:escDepFac>informatica</ns0:escDepFac>
        <ns0:usuario>leonardop</ns0:usuario>
        <ns0:password>4533</ns0:password>
    </ns0:encargado>
    <ns0:encargado>
        <ns0:nombre>Jose</ns0:nombre>
        <ns0:apellido>Jove</ns0:apellido>
        <ns0:ci>45323524</ns0:ci>
        <ns0:escDepFac>informatica</ns0:escDepFac>
        <ns0:usuario>josej</ns0:usuario>
        <ns0:password>1223</ns0:password>
    </ns0:encargado>
    <ns0:encargado>
        <ns0:nombre>Eliseth</ns0:nombre>
        <ns0:apellido>Perez</ns0:apellido>
        <ns0:ci>34234234</ns0:ci>
        <ns0:escDepFac>informatica</ns0:escDepFac>
        <ns0:usuario>elisethp</ns0:usuario>
        <ns0:password>342423</ns0:password>
    </ns0:encargado>

</ns0:usuario>
